import React from "react"

import {
	Paper,
} from '@material-ui/core'

import styles from "./aboutPage.module.scss"


class AboutPage extends React.Component {
	constructor(props){
		super(props)

		this.state = {}
	}

	render(){
		return(
			<Paper className={styles.root}>
				<h1>Detailní popis projektu </h1>
				<p>Krkonoše představují oblast, která na velké části svého území vykazuje znaky diskontinuity vývoje, resp. přerušení kontaktu společnosti s vlastní historií. (V rámci projektu Prameny Krkonoš defnujeme region následovně: soudní okresy k roku 1949 - Trutnov, Maršov, Žacléř, Hostinné, Vrchlabí, Jilemnice, Rokytnice nad Jizerou, Vysoké nad Jizerou). Po druhé světové válce došlo na většině území Krkonoš k zásadní výměně obyvatelstva, když bylo nuceně vysídleno německé etnikum, jež tvořilo až do roku 1945 na dvou třetinách území Krkonoš většinu obyvatelstva. Jeho odchodem nezmizela z regionu pouze paměť, ale ve velké míře i fyzické dokumenty. Historická a kulturní identita Krkonoš je v rámci ČR jedinečná, formovaná vysokohorským přírodním prostředím a několika kolonizačními vlnami a v důsledku toho mnohojazyčným společenstvím. Potřeba opětovného nalézání místní identity vychází v posledních letech velmi silně zejména z řad třetí generace poválečných dosídlenců, která již považuje Krkonoše za svůj domov. Překážkou je zpravidla neznalost němčiny a roztříštěnost informačních zdrojů (tzv. corcontic), které jsou místně, jazykově, typově a institucionálně izolované, často umístěné v soukromých sbírkách v ČR nebo v zahraničí. Některé prameny jsou navíc různým způsobem ohrožené. Jedná se zejména o osobní svědectví pamětníků, soukromé archivy a sbírky, které se navíc z velké části nacházejí v osobním a spolkovém vlastnictví v Německu. Tyto prameny zamýšlíme primárně (s ohledem na míru jejich ohrožení) heuristicky podchytit. Další skupinu pramenů, která si vyžaduje zvláštní pozornost, tvoří odborné časopisy vydávané regionálními paměťovými institucemi v ČR a SRN, populárně-vědné časopisy vydávané různými zájmovými skupinami, ale také nevědecká periodika (typicky krajanské časopisy, obecní a zájmové věstníky, webové stránky regionálních nadšenců apod.) s často odborným obsahem, který je pro výzkum regionálních dějin neopominutelný. Tato periodika bývají často komplikovaně dostupná i ve své fyzické podobě (u nevědeckých se například často neodvádějí ani povinné výtisky), natož aby bylo možné virtuálně vyhledávat podrobnější informace o jejich dílčích částech (článek, kapitola, poznámka, editorial aj.) nebo podle autorů jednotlivých článků.</p>
				<p>Předkládaný projekt přispěje z hlediska NAKI II k naplnění specifckého cíle č. 1.1: Výzkum a jeho uplatnění – historické vědní obory a archeologie, a to zejména prostřednictvím propojením tří tematických priorit: d) vytváření metod dokumentace a prezentace paměťové kultury národa; e) vytváření nástrojů pro podporu udržování a rozvoje historického a kulturního vědomí národní identity; f) výzkum historického vývoje a kultury menšin na historickém území a za hranicemi českého (československého) státu a jejich souvislostí v evropském kontextu.</p> 				
				<p>S ohledem na tyto tři priority má projekt stanoveny tři základní roviny: </p> 				
				<p>1. Prostřednictvím veřejné specializované databáze (báze analytických metadat, hlavní výsledek typu R a vedlejší výstup S) projekt zpřístupní informační prameny o historii a kulturní paměti Krkonoš (tzv. corcontica) z období Československa (1918 – 1992), a to bez ohledu na jejich fyzické umístění a tím přispěje ke specifckému metodologickému nahlížení na regionální dějiny z hlediska informačních pramenů různého typu. Zachytí také v daném čase aktuální stav výzkumu pomocí tematické prezentace sekundárních pramenů a jejich unikátního propojení s prameny primárními a vytvoří tak systematickou základnu pro další výzkum. Dojde k propojení bibliografcké databáze, kterou vytváří Historický ústav AV ČR, s tematickou databází Prameny Krkonoš. V současné době sice existují věcné rejstříky a geografcké rejstříky, ale ty neodpovídají podrobnějšímu členění menších území a především nerefektují historii daného území. Projekt počítá také s napojením jmenných entit z bibliografcké databáze Historického ústavu. Pro obousměrnou výměnu bibliografckých dat bude vytvořen nástroj pro sdílení standardizovaných dat a mapovací schéma pro konverzi dat z databáze HÚ AV ČR do nově vytvářené databáze. Obě databáze se na sebe budou také vzájemně odkazovat. Prameny budou zpřístupněny široké obci uživatelů, zejména badatelům (jejichž práce je komplikována obtížnou dostupností historické a kulturní paměti německy hovořících obyvatel Krkonoš a diskontinuitou vývoje většiny území Krkonoš), a to pomocí inovativního softwarového systému evidence, zpracování a prezentace (výsledek R), jehož hlavní předností bude propojení pramenů, jejich virtuální centralizace, analytický popis (včetně anotace akcentující regionální specifka) a uvedení odkazu na místo jejich fyzického uložení, případně jejich dostupnost v digitální podobě. Pomůckou badatelům bude také specializovaná interaktivní odborná mapa (hlavní výstup Nmap3), která bude na několika úrovních zobrazovat umístění corcontic v Evropě, a to jak z hlediska jejich typologie, tak času vzniku a dílčích témat (pomocí klíčových slov, která budou vytvořena a inkorporována do výsledků S a R). Tato rovina projektu směřuje primárně k naplnění priority 1.1.d, tedy vytváření metod dokumentace a prezentace paměťové kultury národa, a to prostřednictvím výstupů S a R, sekundárně pak k naplnění priority 1.1.e, tedy vytváření nástrojů pro podporu udržování a rozvoje historického a kulturního vědomí národní identity, a to prostřednictvím výstupů R a Nmap3. </p> 				
				<p>2. Další úrovní zamýšleného projektu je analýza, popularizace a odborná prezentace výsledné databáze a možností jejího využití. Jedním z hlavních výstupů projektu tedy bude také výstava “Krkonoše v pramenech, prameny v Krkonoších: obraz Krkonoš v pramenech 20. století” (hlavní výstup Ekrit), včetně kritického katalogu. Výstava bude koncipována jako putovní, takže ji bude možné i po skončení projektu nabídnout také institucím veřejné správy, paměťovým a regionálním institucím. Výstava bude prezentovat rozsáhlou šíři corcontic (informačních zdrojů) k dějinám Krkonoš, jejich typologii, stav a uložení a možnosti jejich využití ve výzkumné, pedagogické i popularizační či vlastivědné činnosti. Výstava předvede i technologické možnosti prezentování corcontic. Tj. nebudou vystavovány samotné corcontica (informační zdroje), ale např. jejich digitální kopie. Tato rovina projektu směřuje primárně k naplnění priority 1.1.e, tedy vytváření nástrojů pro podporu udržování a rozvoje historického a kulturního vědomí národní identity, a to prostřednictvím výstupu Ekrit.</p> 				
				<p>3. Poslední rovinou projektu je zachycení proměn Krkonoš ve 20. století. Jak již bylo zmíněno, Krkonoše jsou specifckým regionem s velmi turbulentním vývojem demografckým a sociálním (exil části českého obyvatelstva v době druhé světové války, následné nucené vysídlení německého obyvatelstva, osídlovací a dosídlovací akce), hospodářským (souvisejícím zejména se zásadními změnami ekonomiky celé země), ale i politickým či správním. Cílem projektu bude představit široké odborné i laické veřejnosti tyto proměny, a to primárně prostřednictvím dvou specializovaných interaktivních odborných map zachycujících změny demografcké, správní a národnostní (hlavní výstup Nmap1), jakož i hospodářské a dopravně-infrastrukturní (hlavní výstup Nmap2). Tato rovina projektu směřuje primárně k naplnění tematické priority 1.1.f, tedy výzkum historického vývoje a kultury menšin na historickém území a za hranicemi českého (československého) státu a jejich souvislostí v evropském kontextu, a to prostřednictvím výstupů Nmap1 a Nmap2.</p> 				
				<p>Z hlediska vedlejších výstupů budou všechny tři výše zmíněné roviny projektu propojeny zejména s výsledkem S (veřejná specializovaná databáze), a také s vedlejšími výstupy M (uspořádání mezioborové vědecké konference, což směřuje k naplnění priorit 1.1.e, tj. vytváření nástrojů pro podporu udržování a rozvoje historického a kulturního vědomí národní identity; 1.1.f, tedy výzkum historického vývoje a kultury menšin na historickém území a za hranicemi českého (československého) státu a jejich souvislostí v evropském kontextu a 1.1.d, tj. vytváření metod dokumentace a prezentace paměťové kultury národa) a B (kolektivní monografe o Krkonoších ve 20. století, která směřuje k naplnění priority 1.1.f, tedy výzkum historického vývoje a kultury menšin na historickém území a za hranicemi českého (československého) státu a jejich souvislostí v evropském kontextu).</p> 				
				<p>Projekt zásadní způsobem přispěje k poznání dějin Krkonoš v období Československa a otevře nové cesty bádání zpřístupněním informací o řadě dosud zcela roztříštěných, a tedy často prakticky téměř nedohledatelných pramenů. Současně bude databáze vzhledem ke své bilingvní povaze (včetně anotací nejdůležitějších corcontic) snadno využitelná i německy mluvícím badatelům, což je důležitým mezinárodním přínosem předkládaného projektu.</p>
			</Paper>
		)
	}
}

export default AboutPage